# Generated by Django 6.0.3 on 2026-03-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('original_website_url', models.URLField()),
                ('redesigned_website_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('EMAIL_SENT', 'Email Sent'), ('OPENED', 'Opened'), ('CLICKED', 'Clicked'), ('REPLIED', 'Replied'), ('PURCHASED', 'Purchased')], default='PENDING', max_length=20)),
                ('purchase_type', models.CharField(choices=[('ONE_TIME', 'One-time (£249)'), ('MONTHLY', 'Monthly (£59/mo)'), ('NONE', 'None')], default='NONE', max_length=20)),
                ('emails_sent_count', models.IntegerField(default=0)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
