# Generated by Django 6.0.3 on 2026-03-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_is_premium_user_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lead',
        ),
        migrations.AddField(
            model_name='website',
            name='hosting_type',
            field=models.CharField(choices=[('PLATFORM', 'Hosted by Cozy Content'), ('SELF', 'Self-hosted by User')], default='PLATFORM', max_length=20),
        ),
    ]
