"""
Django settings for cozybackend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-xfu6lzqui%e^0$n$hqs%&#bu*1(v*&4ec-_jhwdx=v68qtxm87')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['cosycontent.com', 'api.cosycontent.com', 'preview.cosycontent.com', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_celery_beat',
    'api',
    'leads',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTH_USER_MODEL = 'api.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://cosycontent.com",
    "http://cosycontent.com",
]

CSRF_TRUSTED_ORIGINS = [
    "https://cosycontent.com",
    "http://cosycontent.com",
    "https://api.cosycontent.com",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'cozybackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cozybackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'cozy_db'),
        'USER': os.getenv('DB_USER', 'cozy_user'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'cozy_password'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Media files (user-uploaded files)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Stripe Integration ---
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', 'pk_test_placeholder')
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', 'sk_test_placeholder')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', 'whsec_placeholder')
STRIPE_ONE_TIME_PRICE_ID = os.getenv('STRIPE_ONE_TIME_PRICE_ID', 'price_placeholder')
STRIPE_MONTHLY_PRICE_ID = os.getenv('STRIPE_MONTHLY_PRICE_ID', 'price_placeholder')
STRIPE_ANNUAL_PRICE_ID = os.getenv('STRIPE_ANNUAL_PRICE_ID', 'price_placeholder_annual')

# Update Packs
STRIPE_PACK_1_PRICE_ID = os.getenv('STRIPE_PACK_1_PRICE_ID', 'price_pack_1')
STRIPE_PACK_5_PRICE_ID = os.getenv('STRIPE_PACK_5_PRICE_ID', 'price_pack_5')
STRIPE_PACK_10_PRICE_ID = os.getenv('STRIPE_PACK_10_PRICE_ID', 'price_pack_10')
STRIPE_PACK_20_PRICE_ID = os.getenv('STRIPE_PACK_20_PRICE_ID', 'price_pack_20')

# Priority Updates
STRIPE_PRIORITY_MONTHLY_PRICE_ID = os.getenv('STRIPE_PRIORITY_MONTHLY_PRICE_ID', 'price_priority_monthly')

FRONTEND_URL = os.getenv('FRONTEND_URL', 'https://cosycontent.com').rstrip('/')
BACKEND_URL = os.getenv('BACKEND_URL', 'https://api.cosycontent.com').rstrip('/')

# --- Production Security Settings ---
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'Lax'

# --- Default Auto Field ---
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Celery / Redis ---
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/1')
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 60 * 60  # 1h hard cap per task
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

# --- Outscraper ---
OUTSCRAPER_API_KEY = os.getenv('OUTSCRAPER_API_KEY')
OUTSCRAPER_LIMIT_PER_QUERY = int(os.getenv('OUTSCRAPER_LIMIT_PER_QUERY', '100'))

# --- Website audit (PageSpeed) ---
PAGESPEED_API_KEY = os.getenv('PAGESPEED_API_KEY')
AUDIT_BATCH_SIZE = int(os.getenv('AUDIT_BATCH_SIZE', '50'))
AUDIT_OUTDATED_THRESHOLD = int(os.getenv('AUDIT_OUTDATED_THRESHOLD', '50'))  # mobile perf < this -> outdated
AUDIT_REFRESH_DAYS = int(os.getenv('AUDIT_REFRESH_DAYS', '30'))

# --- Outreach email sending (Brevo) ---
# MASTER SWITCH. While False, no outreach emails are ever sent, regardless of
# schedule or manual trigger. Set OUTREACH_ENABLED=True in .env when ready.
OUTREACH_ENABLED = os.getenv('OUTREACH_ENABLED', 'False') == 'True'
# Hard cap on emails sent per UTC day.
OUTREACH_DAILY_LIMIT = int(os.getenv('OUTREACH_DAILY_LIMIT', '50'))
# Max sent per single task run (clamped by the daily limit anyway).
OUTREACH_BATCH_SIZE = int(os.getenv('OUTREACH_BATCH_SIZE', '50'))

# --- Website previews (Stage 2) ---
PREVIEW_BACKFILL_BATCH = int(os.getenv('PREVIEW_BACKFILL_BATCH', '100'))
# Public base where personalised prospect previews are hosted.
PREVIEW_BASE_URL = os.getenv('PREVIEW_BASE_URL', 'https://preview.cosycontent.com').rstrip('/')
# 'Get This Website' CTA target (the purchase / get-started page).
PREVIEW_PURCHASE_URL = os.getenv('PREVIEW_PURCHASE_URL', FRONTEND_URL.rstrip('/') + '/get-started')
PREVIEW_EXPIRY_DAYS = int(os.getenv('PREVIEW_EXPIRY_DAYS', '30'))

# --- OAuth Settings ---
AUTHLIB_OAUTH_CLIENTS = {
    'google': {
        'client_id': os.getenv('GOOGLE_CLIENT_ID'),
        'client_secret': os.getenv('GOOGLE_CLIENT_SECRET'),
        'server_metadata_url': 'https://accounts.google.com/.well-known/openid-configuration',
        'client_kwargs': {'scope': 'openid email profile'},
    }
}
