import Navbar from './Navbar';
import Footer from './Footer';
import { motion } from 'framer-motion';

const PrivacyPolicy = () => {
  return (
    <div className="bg-surface text-on-surface font-body transition-colors duration-300 min-h-screen">
      <Navbar />
      <main className="pt-44 pb-32 px-8">
        <div className="max-w-4xl mx-auto bg-surface-container-low p-12 rounded-[2.5rem] border border-outline-variant/20 shadow-xl">
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-5xl font-black mb-8 tracking-tighter"
          >
            Privacy Policy
          </motion.h1>
          <p className="text-on-surface-variant mb-12 font-bold italic">Last updated: April 02, 2026</p>
          
          <div className="prose dark:prose-invert max-w-none space-y-8 text-on-surface-variant font-medium leading-relaxed">
            <p>
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
            </p>
            <p>
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
            </p>

            <h2 className="text-2xl font-bold text-on-surface mt-12 mb-4">Interpretation and Definitions</h2>
            <h3 className="text-xl font-bold text-on-surface">Interpretation</h3>
            <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

            <h3 className="text-xl font-bold text-on-surface">Definitions</h3>
            <p>For the purposes of this Privacy Policy:</p>
            <ul className="list-disc pl-6 space-y-4">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where “control” means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Cosy Content Limited, 62 Wilsden Avenue, Luton, Bedfordshire, LU1 5HP.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: United Kingdom</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>Website</strong> refers to Cosy Content Limited, accessible from https://cosycontent.com</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>

            <h2 className="text-2xl font-bold text-on-surface mt-12 mb-4">Collecting and Using Your Personal Data</h2>
            <h3 className="text-xl font-bold text-on-surface">Types of Data Collected</h3>
            <h4 className="text-lg font-bold text-on-surface">Personal Data</h4>
            <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Payment details (processed securely via third-party providers). We do not store your full payment details</li>
              <li>Usage Data</li>
            </ul>

            <h3 className="text-xl font-bold text-on-surface mt-8">Usage Data</h3>
            <p>Usage Data is collected automatically when using the Service. It may include information such as Your Device’s IP address, browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, and other diagnostic data.</p>

            <h3 className="text-xl font-bold text-on-surface mt-8">Tracking Technologies and Cookies</h3>
            <p>We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.</p>
            
            <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

            <h2 className="text-2xl font-bold text-on-surface mt-12 mb-4">Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc pl-6 space-y-4">
              <li>To provide and maintain our Service.</li>
              <li>To manage Your Account.</li>
              <li>For the performance of a contract.</li>
              <li>To contact You.</li>
              <li>To provide You with news, special offers and general information.</li>
              <li>To manage Your requests.</li>
            </ul>

            <h2 className="text-2xl font-bold text-on-surface mt-12 mb-4">Security of Your Personal Data</h2>
            <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>

            <h2 className="text-2xl font-bold text-on-surface mt-12 mb-4">Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>By email: contact@cosycontent.com</li>
              <li>By visiting this page on our website: https://cosycontent.com/contact/</li>
              <li>By phone number: +44 (0) 7864 670 284</li>
            </ul>
          </div>
        </div>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
